version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    network_mode: host
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: localhost
            port: 5432
            user: prisma
            password: prisma
  server:
    network_mode: host
    image: ncognita/server
    depends_on:
      - prisma
    restart: always
